name: My Workflow

# Controls when the action will run. 
on: push
  #push:
    #branches:
      #- 'master/*'
env:
   message: 'world'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
       # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Checkout repo content 
        #uses: actions/checkout@v2 # checkout the repository content to github runner.
        uses: actions/checkout@master
      - name: Say Something
        run: |
           echo "Hello ${message}"
           echo "Again Welcome"
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
        # Semantic version range syntax or exact version of a Python version
          python-version: 3.8 #Install the python needed ,'3.x' 0r 3.8
        # Optional - x64 or x86 architecture, defaults to x64
          #architecture: 'x64'
      - name: Initialisation
        run: echo "Welcome to the NEST static analysis build"
        env:
          key: xNEST_BUILD_TYPE= STATIC_CODE_ANALYSIS
      #- name: execute py script # run the run.py to get the latest data  
        #run: |
          #python run.py
        #env: 
          #xNEST_BUILD_TYPE= STATIC_CODE_ANALYSIS
        #run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip setuptools
           python -m pip install scipy junitparser numpy nose cython matplotlib terminaltables
           pip list
           g++ --version
           #chmod +x extras/travis_build.sh
           set -o pipefail
           
